language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- 3.8-dev
- nightly
install:
#  - pip install -r requirements.txt
  - pip install .
#script: pytest
script: microftpcmd --help
deploy:
  provider: pypi
  user: __token__
  password:
    secure: YUNPFhTNQiUTZ0kkozko9FeThsSDlFucDwo0QAHQB3sKnPzav6VwYYb4LWdPxt9UUuE++S58s0ExMybhi0c68YEESH6XyVIDWFdoE6U/NsTTMZLYfXINdzv3oW8rF57F744KFnhezJnDc8bUqU42s0YkVrVGc7NpV8D+uo7C8QOsHHuJ8qSs7D2hnbL37zGxz7lL3yYPiucRamhnOuUqpX8JAgDedTRAJ9cdLZHJqhIi+RBxQLGr6q3wzrVGBMe8L51XHvMo1pNUy2jOL4VIHg9c08odHtv4Nk3czEC+Xq+8Vyx4kg6I4ggVvFIURxWXQs/M62+f8menipnkYQQyofzSZcm0RS1bCDfQArY9pefZFtU1h7JwAZUwNAwxbjQzCtBsAFmQTAG+clngX5/kZ48Hxj2w7BUg8jjv5nWGP49/dJorOe2qLF56lPdXZdfNHXwsl5Qk/KHohlTjWOAYRfMjn/VwOekr3qdKfmol2J4ODHEaUxfxllahZqBTj5/en0AF3G0XgV5YkQGye9e4q9mWXuPk1auNNCY5+X2Czy3ZF/LWMXvJ5CNY6WTWTrQysHtSPjhekCrPgp8pqsM4zJGE4O3Y9q0RM5i5xKPZYuvMtgzY15NgD1pH3TI2oS/R1FjrIgJ4nHfvoeZclY3Rq34dcTSbVZtjMoqnf2Xd7mk=
  on:
    tags: true
